### ISSUE TITLE
Update vendor

### ISSUE THREAD

**Issue by josamho** [FnacMarketplace/fnacapiclient#1]
Hello, 

I'm working on a Symfony 2.8 project, and i need to use this API.
I have a problem with the version of Serializer,
I have already a Serializer version in my core project of Symfony and this isn't the same version of your package.
It is like we can't have 2 versions of Serializer and can't use the api because of that...
Have you planned a update of the different packages ? 

Audrey,

**Comment by FnacMarketplace** [comment]
Hello,

I am working on this issue. 

Best regards,

Benoit,

**Comment by FnacMarketplace** [comment]
Hello,

Please use the new version tagged with v2.0 which is compatible with symfony 2.8.

Best regards,

Benoit
