### ISSUE TITLE
Deprecated: iconv_set_encoding(): Use of iconv.internal_encoding is deprecated

### ISSUE THREAD

**Issue by Klemart3D** [FnacMarketplace/fnacapiclient#2]
This [Zend issue](https://github.com/zendframework/zendframework/issues/6218) can be solved by replacing in _/vendor/zendframework/zend-validator/src/Hostname.php_:

`iconv_set_encoding('internal_encoding', 'UTF-8');`(on line 491) by:
```php
if (PHP_VERSION_ID < 50600) {
    iconv_set_encoding('internal_encoding', 'UTF8');
} else {
    ini_set('default_charset', 'UTF8');
}
```

And `iconv_set_encoding('internal_encoding', $origenc);` (line 587) by:
```php
if (PHP_VERSION_ID < 50600) {
    iconv_set_encoding('internal_encoding', $origenc);
} else {
    ini_set('default_charset', $origenc);
}
```
Original error after fresh install of _fnacapiclient_ + `composer install`:

![](https://i.imgur.com/MCfcZmG.jpg)

**Comment by FnacMarketplace** [comment]
Hello,

Zend version has been updated to 2.3.2 which solves the problem.

#3 

Best regards,
Benoit,
